spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 111111

  thymeleaf:
    mode: HTML5
    cache: false
    encoding: utf-8
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    #保存的日期格式

  messages:
    encoding: utf-8
    basname: messages

pagehelper:                #分页插件
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params:

mybatis:
  type-aliases-package: com.lz.blog.po   #设置别名
  mapper-locations: classpath:mapper/*.xml   #?指定myBatis的核心配置文件与Mapper映射文件


logging:  #日志级别
  level:
    root: info
    com.lz.blog.dao: debug

  file:
    name: log/blog-dev.log




#配置评论头像
comment.avatar: static/images/avatar.png

